# This project used to live in Gitlab.
# But you know, open source projects
# are not so discoverable over there :(

image: golang:1.14.0

stages:
  - deps
  - test
  - build

# Globals

variables:
  REPO_NAME: gitlab.com/unmultimedio/samplr

before_script:
  - export GO111MODULE=on
  - go version
  - env
  - go env
  - find *

cache:
  paths:
    - vendor/

# Jobs

pull dependencies:
  stage: deps
  script: 
    - make deps

run linters:
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:golangci-lint-alpine
  stage: test
  script:
    - apk add --update make
    - make checks

unit tests:
  stage: test
  script:
    - make test

build:
  stage: build
  variables:
  script:
  - GOOS=darwin GOARCH=amd64 go build -o build/samplr_mac
  - GOOS=linux GOARCH=amd64 go build -o build/samplr_linux
  artifacts:
    paths:
    - build/samplr_mac
    - build/samplr_linux

