# Write here your regex matches for
# filenames that you want to include
# or exclude from the samplr generation
# Be careful to indent using spaces

includes:
  - ^examples

excludes:
  - \.go$
  - \.sample\.
