# Some sample comments
foo: foo

#samplr#secret: replace me
secret: should not render

# Should not render #hsamplr#previous_line: successfully hidden
previous_line: this should not render

#ssamplr# SECRET! This should not render
this_line: should render normally

bar: bar
