# Some sample comments
foo: foo

#samplr#secret: replace me
secret: replace me

previous_line: successfully hidden

this_line: should render normally

bar: bar

some:
  nested:
    #samplr#    data: secret
    data: secret

    # next key line should not render
    data: public
