# Some comments
shareable_config: foo
#samplr#secret_config: mocked
secret_config: mocked
public_config: bar
#samplr## a comment that includes mocks
# a comment that includes mocks

# blank lines

foo: foo
#samplr#bar: barpublic
bar: barpublic
