package cmd

var comments = map[string]string{
	".c":    "// File autogenerated. Your changes may be overwritten. DO NOT EDIT.\n\n",
	".cpp":  "// File autogenerated. Your changes may be overwritten. DO NOT EDIT.\n\n",
	".go":   "// File autogenerated. Your changes may be overwritten. DO NOT EDIT.\n\n",
	".java": "// File autogenerated. Your changes may be overwritten. DO NOT EDIT.\n\n",
	".js":   "// File autogenerated. Your changes may be overwritten. DO NOT EDIT.\n\n",
	".py":   "# File autogenerated. Your changes may be overwritten. DO NOT EDIT.\n\n",
	".rb":   "# File autogenerated. Your changes may be overwritten. DO NOT EDIT.\n\n",
	".rs":   "// File autogenerated. Your changes may be overwritten. DO NOT EDIT.\n\n",
	".yml":  "# File autogenerated. Your changes may be overwritten. DO NOT EDIT.\n\n",
}

// CommentFor returns a "DO NOT EDIT." like comment
// to include as a header in a generated file.
func CommentFor(fileExtension string) string {
	return comments[fileExtension]
}
