name: Release builds

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: make deps

    - name: Build binaries
      run: |
        GOOS=linux GOARCH=amd64 go build -o ./bin/samplr_linux
        GOOS=darwin GOARCH=amd64 go build -o ./bin/samplr_mac

    - name: Upload asset linux
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/samplr_linux
        asset_name: samplr-${{ github.event.release.tag_name }}-linux
        asset_content_type: binary/octet-stream

    - name: Upload asset mac
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/samplr_mac
        asset_name: samplr-${{ github.event.release.tag_name }}-mac
        asset_content_type: binary/octet-stream
